apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-v1-free5gc-udr-udr
  labels:
    helm.sh/chart: free5gc-udr-0.2.4
    app.kubernetes.io/name: free5gc-udr
    app.kubernetes.io/instance: free5gc-v1
    app.kubernetes.io/version: "v3.2.1"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: udr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: free5gc-udr
      app.kubernetes.io/instance: free5gc-v1
      project: free5gc
      nf: udr
  template:
    metadata:
      annotations:

        checksum/config: 4cdcc8ceff5d07228b527681593baad4f495fd2f2b75bec5b3d00580d4603080
      labels:
        app.kubernetes.io/name: free5gc-udr
        app.kubernetes.io/instance: free5gc-v1
        project: free5gc
        nf: udr
    spec:
      imagePullSecrets:
        []
      securityContext:
        {}
      initContainers:
      - name: wait-nrf
        image: towards5gs/initcurl:1.0.0
        env:
        - name: DEPENDENCIES
          value: http://nrf-nnrf:8000
        command: ['sh', '-c', 'set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;']
      containers:
      - name: udr
        image: towards5gs/free5gc-udr:v3.2.1
        imagePullPolicy: Always
        securityContext:
            {}
        ports:
        - containerPort: 80
        command: ["./udr"]
        args: ["-c", "../config/udrcfg.yaml"]
        env:
          - name: DB_URI
            value: mongodb://mongodb/free5gc
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: udr-volume
        resources:
            requests:
              cpu: 100m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []

      volumes:
      - name: udr-volume
        projected:
          sources:
          - configMap:
              name: udr-configmap

