apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-configmap
  labels:
    app: free5gc
data:
  nssfcfg.yaml: |
    info:
      version: 1.0.1
      description: NSSF initial local configuration

    configuration:
      serviceNameList:
        - nnssf-nsselection
        - nnssf-nssaiavailability

      sbi:
        scheme: http
        registerIPv4: nssf-nnssf # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 80
        tls:
          key: config/TLS/nssf.key
          pem: config/TLS/nssf.pem

      nrfUri: http://nrf-nnrf:8000

      nsiList:
        - snssai:
            sst: 1
            sd: 010203
          nsiInformationList:
            - nrfId: http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances
              nsiId: 22
      nssfName: NSSF
      supportedPlmnList:
        - mcc: 208
          mnc: 93
      supportedNssaiInPlmnList:
        - plmnId:
            mcc: 208
            mnc: 93
          supportedSnssaiList:
            - sst: 1
              sd: 010203
      taList:
        - tai:
            plmnId:
              mcc: 208
              mnc: 93
            tac: 1
          accessType: 3GPP_ACCESS
          supportedSnssaiList:
            - sst: 1
              sd: 010203

    logger:
      NSSF:
        ReportCaller: false
        debugLevel: info

