apiVersion: v1
kind: Service
metadata:
  name: udm-nudm
  labels:
    helm.sh/chart: free5gc-udm-0.2.4
    app.kubernetes.io/name: free5gc-udm
    app.kubernetes.io/instance: free5gc-v1
    app.kubernetes.io/version: "v3.2.1"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: udm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: free5gc-udm
    app.kubernetes.io/instance: free5gc-v1
    project: free5gc
    nf: udm

