apiVersion: v1
kind: Service
metadata:
  name: webui-service
  labels:
    helm.sh/chart: free5gc-webui-0.1.4
    app.kubernetes.io/name: free5gc-webui
    app.kubernetes.io/instance: free5gc-v1
    app.kubernetes.io/version: "v3.2.1"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: webui
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: free5gc-webui
    app.kubernetes.io/instance: free5gc-v1
    project: free5gc
    nf: webui

