apiVersion: v1
kind: Service
metadata:
  name: nrf-nnrf
  labels:
    helm.sh/chart: free5gc-nrf-0.2.4
    app.kubernetes.io/name: free5gc-nrf
    app.kubernetes.io/instance: free5gc-v1
    app.kubernetes.io/version: "v3.2.1"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: nrf
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: free5gc-nrf
    app.kubernetes.io/instance: free5gc-v1
    project: free5gc
    nf: nrf

