apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-v1-free5gc-ausf-ausf
  labels:
    helm.sh/chart: free5gc-ausf-0.2.4
    app.kubernetes.io/name: free5gc-ausf
    app.kubernetes.io/instance: free5gc-v1
    app.kubernetes.io/version: "v3.2.1"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: free5gc-ausf
      app.kubernetes.io/instance: free5gc-v1
      project: free5gc
      nf: ausf
  template:
    metadata:
      annotations:

        checksum/config: d9e61ecac6e2c1c0d03b130d5f49e334d9c94cc9773f12a01321517d180b4f5e
      labels:
        app.kubernetes.io/name: free5gc-ausf
        app.kubernetes.io/instance: free5gc-v1
        project: free5gc
        nf: ausf
    spec:
      imagePullSecrets:
        []
      securityContext:
        {}
      initContainers:
      - name: wait-nrf
        image: towards5gs/initcurl:1.0.0
        env:
        - name: DEPENDENCIES
          value: http://nrf-nnrf:8000
        command: ['sh', '-c', 'set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;']
      containers:
      - name: ausf
        image: towards5gs/free5gc-ausf:v3.2.1
        imagePullPolicy: Always
        securityContext:
            {}
        ports:
        - containerPort: 80
        command: ["./ausf"]
        args: ["-c", "../config/ausfcfg.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: ausf-volume
        resources:
            requests:
              cpu: 100m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []

      volumes:
      - name: ausf-volume
        projected:
          sources:
          - configMap:
              name: ausf-configmap

