apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: free5gc-v1-free5gc-ausf-hpa
  labels:
    helm.sh/chart:
    app.kubernetes.io/name:
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: free5gc-v1-free5gc-ausf-ausf
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80

