apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-v1-free5gc-amf-amf
  labels:
    helm.sh/chart: free5gc-amf-0.2.4
    app.kubernetes.io/name: free5gc-amf
    app.kubernetes.io/instance: free5gc-v1
    app.kubernetes.io/version: "v3.2.1"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: free5gc-amf
      app.kubernetes.io/instance: free5gc-v1
      project: free5gc
      nf: amf
  template:
    metadata:
      annotations:

        k8s.v1.cni.cncf.io/networks: '[
            { "name": "n2network-amf",
              "interface": "n2",
              "ips": [ "10.100.50.249/29" ],
              "gateway": [ "10.100.50.254" ]
            }]'
        checksum/config: e339b9a5c321127631b3a06cf737f488440fb5407ed39816527dc6b7d36bf0d6
      labels:
        app.kubernetes.io/name: free5gc-amf
        app.kubernetes.io/instance: free5gc-v1
        project: free5gc
        nf: amf
    spec:
      imagePullSecrets:
        []
      securityContext:
        {}
      initContainers:
      - name: wait-nrf
        image: towards5gs/initcurl:1.0.0
        env:
        - name: DEPENDENCIES
          value: http://nrf-nnrf:8000
        command: ['sh', '-c', 'set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;'] 
      containers:
      - name: amf
        image: towards5gs/free5gc-amf:v3.2.1
        imagePullPolicy: Always
        securityContext:
            {}
        ports:
        - containerPort: 80
        ports:
        - name: namf
          containerPort: 80
        - name: n2
          containerPort: 38412
          protocol: SCTP
        command: ["./amf"]
        args: ["-c", "../config/amfcfg.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: amf-volume
        resources:
            requests:
              cpu: 150m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []

      volumes:
      - name: amf-volume
        projected:
          sources:
          - configMap:
              name: amf-configmap

