apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-v1-free5gc-smf-smf
  labels:
    helm.sh/chart: free5gc-smf-0.2.4
    app.kubernetes.io/name: free5gc-smf
    app.kubernetes.io/instance: free5gc-v1
    app.kubernetes.io/version: "v3.2.1"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: free5gc-smf
      app.kubernetes.io/instance: free5gc-v1
      project: free5gc
      nf: smf
  template:
    metadata:
      annotations:

        k8s.v1.cni.cncf.io/networks: '[
            { "name": "n4network-smf",
              "interface": "n4",
              "ips": [ "10.100.50.244/29" ],
              "gateway": [ "10.100.50.246" ]
            }]'
        checksum/config: 962085d421cc0ad2a6fdd4ec8f1c19abf01e1abed98a211d7c380fa468acb0de
      labels:
        app.kubernetes.io/name: free5gc-smf
        app.kubernetes.io/instance: free5gc-v1
        project: free5gc
        nf: smf
    spec:
      imagePullSecrets:
        []
      securityContext:
        {}
      initContainers:
      - name: wait-nrf
        image: towards5gs/initcurl:1.0.0
        env:
        - name: DEPENDENCIES
          value: http://nrf-nnrf:8000
        command: ['sh', '-c', 'set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;']
      containers:
      - name: smf
        image: towards5gs/free5gc-smf:v3.2.1
        imagePullPolicy: Always
        securityContext:
            {}
        ports:
        - name: nsmf
          containerPort: 80
        - name: n4
          containerPort: 8805
          protocol: UDP
        command: ["./smf"]
        args: ["-c", "../config/smfcfg.yaml", "-u", "../config/uerouting.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: smf-volume
        resources:
            requests:
              cpu: 100m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []

      volumes:
      - name: smf-volume
        projected:
          sources:
          - configMap:
              name: smf-configmap
              items:
              - key: smfcfg.yaml
                path: smfcfg.yaml
              - key: uerouting.yaml
                path: uerouting.yaml

